#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-uamqp
Version  : 1.5.3
Release  : 53
URL      : https://files.pythonhosted.org/packages/b8/68/d13caa61398064a2f4aea5d3ea3cf78dc449eae9b0ebd5ad08c0f3d7c180/uamqp-1.5.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/b8/68/d13caa61398064a2f4aea5d3ea3cf78dc449eae9b0ebd5ad08c0f3d7c180/uamqp-1.5.3.tar.gz
Summary  : AMQP 1.0 Client Library for Python
Group    : Development/Tools
License  : MIT
Requires: pypi-uamqp-filemap = %{version}-%{release}
Requires: pypi-uamqp-lib = %{version}-%{release}
Requires: pypi-uamqp-license = %{version}-%{release}
Requires: pypi-uamqp-python = %{version}-%{release}
Requires: pypi-uamqp-python3 = %{version}-%{release}
Requires: pypi(six)
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : openssl-dev
BuildRequires : pypi(certifi)
BuildRequires : pypi(six)
BuildRequires : python3-dev

%description
================

%package filemap
Summary: filemap components for the pypi-uamqp package.
Group: Default

%description filemap
filemap components for the pypi-uamqp package.


%package lib
Summary: lib components for the pypi-uamqp package.
Group: Libraries
Requires: pypi-uamqp-license = %{version}-%{release}
Requires: pypi-uamqp-filemap = %{version}-%{release}

%description lib
lib components for the pypi-uamqp package.


%package license
Summary: license components for the pypi-uamqp package.
Group: Default

%description license
license components for the pypi-uamqp package.


%package python
Summary: python components for the pypi-uamqp package.
Group: Default
Requires: pypi-uamqp-python3 = %{version}-%{release}

%description python
python components for the pypi-uamqp package.


%package python3
Summary: python3 components for the pypi-uamqp package.
Group: Default
Requires: pypi-uamqp-filemap = %{version}-%{release}
Requires: python3-core
Provides: pypi(uamqp)
Requires: pypi(certifi)
Requires: pypi(six)

%description python3
python3 components for the pypi-uamqp package.


%prep
%setup -q -n uamqp-1.5.3
cd %{_builddir}/uamqp-1.5.3
pushd ..
cp -a uamqp-1.5.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656365263
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-uamqp
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/build_all/packaging/linux/debian/copyright %{buildroot}/usr/share/package-licenses/pypi-uamqp/fcd11f2e53968b872b48efbb6cf2a18c5a0d04e5
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/build_all/packaging/linux/debian/copyright %{buildroot}/usr/share/package-licenses/pypi-uamqp/b936129838be63462c2583bfd059d8736f39ab87
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/azure-macro-utils-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/umock-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/c4770fd76438e6ead5e333d693d65b1b68d924b0
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/umock-c/deps/azure-macro-utils-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/umock-c/deps/ctest/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/umock-c/deps/ctest/deps/azure-macro-utils-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/umock-c/deps/testrunner/deps/azure-macro-utils-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/testtools/ctest/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/testtools/ctest/deps/azure-macro-utils-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/testtools/testrunner/deps/azure-macro-utils-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-c-testrunnerswitcher/deps/azure-macro-utils-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-ctest/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-ctest/deps/azure-macro-utils-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/azure-macro-utils-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/umock-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/c4770fd76438e6ead5e333d693d65b1b68d924b0
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/umock-c/deps/azure-macro-utils-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/umock-c/deps/ctest/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/umock-c/deps/ctest/deps/azure-macro-utils-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
cp %{_builddir}/uamqp-1.5.3/src/vendor/azure-uamqp-c/deps/umock-c/deps/testrunner/deps/azure-macro-utils-c/LICENSE %{buildroot}/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-pypi-uamqp

%files lib
%defattr(-,root,root,-)
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-uamqp/47e4690f60befa1918e5ac38723973fe4cf04e9b
/usr/share/package-licenses/pypi-uamqp/b936129838be63462c2583bfd059d8736f39ab87
/usr/share/package-licenses/pypi-uamqp/c4770fd76438e6ead5e333d693d65b1b68d924b0
/usr/share/package-licenses/pypi-uamqp/fcd11f2e53968b872b48efbb6cf2a18c5a0d04e5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
